version: "2"
services:
  web:
    build:
      context: ./apps/flask-example-00
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./apps/flask-example-00/:/code
    depends_on:
      - redis
  redis:
    image: redis
