version: "2"
services:
  web:
    build:
      # Specify our app directory as the context
      context: ./apps/flask-example-00
      # Use the Dockerfile that exists within the directory we specified above
      dockerfile: ./Dockerfile
    ports:
      # Flask server
      - "5000:5000"
      # Flask server debug port
      - "5678:5678"
    environment:
      # Specify the path within our Docker container that contains our application code
      FLASK_APP: /code/app.py
      FLASK_ENV: development
    command: flask run --host=0.0.0.0 --port=5000
    volumes:
      # Map our local directory to our Docker application root so that any changes we make are immediately available
      - ./apps/flask-example-00/:/code
    depends_on:
      - redis
  redis:
    image: redis
